biomejs/biome-intellij

LICENSE-APACHE, LICENSE-MIT
This PR adds both the `MIT` and `Apache-2.0` licenses to the repository.
The plugin was previously licensed under MIT only, and all contributors accepted to use a dual license, as voted in #8.
=> chore: add licenses

src/main/resources/META-INF/plugin.xml
this fixes #33
The error appeared because the text attribute was missing in the action. The action now appears in the menu.
=> fix: Add text attribute to ReformatWithBiomeAction

src/main/kotlin/com/github/biomejs/intellijbiome/settings/BiomeSettingsState.kt
since 1.6 .vue .svelte and .astro are [partially supported](https://biomejs.dev/internals/language-support/#html-super-languages-support)
when running biome on all files these files now get formatted and linted but the plugin just ignores them.
which is kinda confusing.
Thanks for the great work!
=> add .vue,.svelte,.astro to default files

CHANGELOG.md, README.md
The README has been updated to indicate compatibility with the new version of IntelliJ (2024.1), and similar updates have been applied for WebStorm, AppCode, PhpStorm, and RubyMine. In the CHANGELOG, a bug fix related to the IntelliJ version update has been added.
=> Update README and CHANGELOG for new IntelliJ version

README.md, src/main/kotlin/com/github/biomejs/intellijbiome/BiomePackage.kt, src/main/kotlin/com/github/biomejs/intellijbiome/BiomeStdinRunner.kt, src/main/kotlin/com/github/biomejs/intellijbiome/actions/BiomeCheckOnSaveAction.kt, src/main/kotlin/com/github/biomejs/intellijbiome/actions/ReformatWithBiomeAction.kt, src/main/kotlin/com/github/biomejs/intellijbiome/listeners/BiomeEditorPanelListener.kt, src/main/kotlin/com/github/biomejs/intellijbiome/lsp/BiomeLspServerSupportProvider.kt, src/main/kotlin/com/github/biomejs/intellijbiome/services/BiomeServerService.kt, src/main/kotlin/com/github/biomejs/intellijbiome/settings/BiomeSettings.kt
Hi
I really liked the speed and easy use of biome. But unfortunately without pretty support in IDE it's really hard to bring it to my company now. So I tried to solve current issues, that block.
1. https://github.com/biomejs/biome-intellij/issues/44
The problem is that in case if file wasn't saved first, it was deleted entirely. Also I think it should be valid to use all options (applySafeFixesOnSave, applyUnsafeFixesOnSave) when Reformat with Biome is triggered, cause this is something that everyone expect.
2. https://github.com/biomejs/biome-intellij/issues/42
This is done for Automatic setup. I didn't come up with something better, that lookup to biome config from file upwards the project root. So it will use this file as config for formatting and LSP then. LSP will restart, if editor …
=> allow intellij project to work with different biome configs

src/main/kotlin/com/github/biomejs/intellijbiome/BiomeStdinRunner.kt
Previously, format fixes were not applied unless lint fixes were enabled.
=> fix: apply formatting fixes when no lint fixes are enabled

src/main/resources/META-INF/plugin.xml
JetBrains does not seem to recognize `com.intellij.modules.javascript` as compatible with all their IDEs except IntelliJ Ultimate. It works perfectly fine when installed over disk, but the latest version on the store for Webstorm and most IDEs is still 1.1.0.
Reverts biomejs/biome-intellij#57
=> Revert "Add support for RustRover"

build.gradle.kts
Checked with command `./gradlew properties | grep version:`:
- Before: `version: valueof(GradlePropertyValueSource)`
- After: `version: 1.2.1`
=> fix: set plugin version in gradle properties

.github/workflows/_build.yaml
Due the migration to  intellj plugin platform the build path/filename changed from `build/distributions/Biome-1.2.0.zip` to `build/distributions/intellij-biome-1.2.1.zip`.
If i understand the release pipeline correctly, it builds the plugin and upload the artifacts for the next steps. So i only need to upload `intellij-biome-x.y.z.zip` as `Biome-x.y.z.zip`.
@ematipico I don't know to test the github actions. Maybe you can run the nighly-release-actions based on this branch before merge? I'm sorry that this release needs three PRs (until now :crossed_fingers:).
=> fix: upload build artifact

.github/workflows/publish.yaml
Setup java and gradle should fix error: https://github.com/biomejs/biome-intellij/actions/runs/10491164584/job/29059934829
> [!CAUTION]
> Dependency requires at least JVM runtime version 17. This build uses a Java 11 JVM.
https://github.com/biomejs/biome-intellij/blob/67c2c5cc004f3862c53cccd14cd8e8133242704b/.github/workflows/publish.yaml#L31-L40
Source: https://github.com/JetBrains/intellij-platform-plugin-template/blob/main/.github/workflows/release.yml
Display downloaded files to debug error: https://github.com/biomejs/biome-intellij/actions/runs/10491164584/job/29059934508
> [!CAUTION]
> Run mv "Biome-1.2.1-nightly.9b01429.zip" biome.zip
> mv: cannot stat 'Biome-1.2.1-nightly.9b01[4](https://github.com/biomejs/biome-intellij/actions/runs/10491164584/job/29059934508#step:7:5)29.zip': …
=> chore(release): setup java and gradle, display structure of downloaded artifact(s)

.github/workflows/publish.yaml
I don't know why, but the downloaded ZIP file has the prefix "intellij-biome-" instead of "Biome-" in GitHub Action "Publish to GitHub Releases":
https://github.com/biomejs/biome-intellij/actions/runs/10522456811/job/29155394740#step:5:17
Based on the github action log, I would have expected "Biome-": 
https://github.com/biomejs/biome-intellij/actions/runs/10522456811/job/29155135022#step:10:23
When I download the artifact on my system, I get the file with a "Biome-" prefix: 
https://github.com/biomejs/biome-intellij/actions/runs/10522456811/artifacts/1846129195
=> fix(release): rename artifact with "intellij-biome-" instead "Biome-" prefix

src/main/kotlin/com/github/biomejs/intellijbiome/BiomePackage.kt, src/main/kotlin/com/github/biomejs/intellijbiome/BiomeRunner.kt, src/main/kotlin/com/github/biomejs/intellijbiome/BiomeStdinRunner.kt, src/main/kotlin/com/github/biomejs/intellijbiome/actions/BiomeCheckRunner.kt
Since [Biome v1.8.0](https://github.com/biomejs/biome/blob/main/CHANGELOG.md#180-2024-06-04) the cli arguments have changed from `--apply` and `--apply-unsafe` to `--write` and `--unsafe`.
In https://github.com/biomejs/biome-intellij/pull/85 we updated the cli flags, but dropped backwards compatibility.
This PR checks the running biome version to add backwards compatibility to biome prior to 1.8.0. This PR also sets `--skip-errors` to skip files containing syntax errors instead of throw an error.
Fixes #89 #90 #95
=> feat: set flags based on biome-version to add backwards compatibility

src/main/kotlin/com/github/biomejs/intellijbiome/BiomePackage.kt
fixes https://github.com/biomejs/biome-intellij/issues/111 by normalizing nightly biome package versions to the expected `major.minor.patch` format without the `-nightly.hash` postfix before splitting by ".".
=> fix: resolve plugin crash when using nightly biome releases

src/main/kotlin/com/github/biomejs/intellijbiome/BiomeConfigIconProvider.kt, src/main/kotlin/com/github/biomejs/intellijbiome/settings/BiomeConfigurable.kt, src/main/kotlin/com/github/biomejs/intellijbiome/settings/BiomeOnSaveApplySafeFixesActionInfo.kt, src/main/kotlin/com/github/biomejs/intellijbiome/settings/BiomeOnSaveFormatActionInfo.kt, src/main/kotlin/com/github/biomejs/intellijbiome/settings/BiomeOnSaveInfoProvider.kt, src/main/resources/META-INF/plugin.xml, src/main/resources/messages/BiomeBundle.properties
=> feat: add support for Biome config icons and improve save actions

src/main/kotlin/com/github/biomejs/intellijbiome/BiomePackage.kt, src/main/kotlin/com/github/biomejs/intellijbiome/BiomeTargetRun.kt, src/main/kotlin/com/github/biomejs/intellijbiome/lsp/BiomeLspServerSupportProvider.kt
Refactor BiomePackage to enhance dependency resolution and executable path detection, allowing better integration with project files. Adjusted LSP server startup logic to support fine-grained package resolution and configuration modes. Simplified BiomeTargetRunBuilder behavior to align with manual or automatic configuration modes.
=> fix: improve BiomePackage and LSP startup logic

gradle.properties, src/main/kotlin/com/github/biomejs/intellijbiome/BiomePackage.kt, src/main/kotlin/com/github/biomejs/intellijbiome/GeneralProcessCommandBuilder.kt, src/main/kotlin/com/github/biomejs/intellijbiome/NodeProcessCommandBuilder.kt, src/main/kotlin/com/github/biomejs/intellijbiome/ProcessCommandBuilder.kt, src/main/kotlin/com/github/biomejs/intellijbiome/ProcessCommandParameter.kt, src/main/kotlin/com/github/biomejs/intellijbiome/lsp/BiomeLspServerSupportProvider.kt
Closes #49 
This pull request adds support for running Biome on Node.js interpreter on WSL 2.
IntelliJ's Node.js execution supports converting a local path to WSL path or vice versa.
Reproduction steps:
1. Install a distribution on WSL 2.
2. Install WebStorm on Windows (do not use JetBrains Gateway).
3. Setup Node.js interpreter that runs on WSL 2:
4. Install Biome plugin.
5. Open a project that has `biome.json`.
=> fix: support running Biome on WSL Node.js interpreter

src/main/kotlin/com/github/biomejs/intellijbiome/BiomePackage.kt, src/main/kotlin/com/github/biomejs/intellijbiome/BiomeTargetRun.kt, src/main/kotlin/com/github/biomejs/intellijbiome/GeneralProcessCommandBuilder.kt, src/main/kotlin/com/github/biomejs/intellijbiome/NodeProcessCommandBuilder.kt, src/main/kotlin/com/github/biomejs/intellijbiome/ProcessCommandBuilder.kt, src/main/kotlin/com/github/biomejs/intellijbiome/lsp/BiomeLspServerSupportProvider.kt
Follow-up of #131
Closes #72
Closes #83
By the fix above, Biome now runs on WSL successfully. However no diagnostics are shown on the editor. Biome responses diagnostics with their file path on LSP, and it is needed to convert the file path on WSL to local path. I added `findLocalFileByPath` implementation in `BiomeLspServerDescriptor` with some refactorings around `BiomeTargetRun`.
=> fix: convert WSL path to local path and vice versa

sandbox/bar/package.json, sandbox/foo/package.json, sandbox/pnpm-lock.yaml, src/main/kotlin/com/github/biomejs/intellijbiome/lsp/BiomeLspServerSupportProvider.kt, src/main/kotlin/com/github/biomejs/intellijbiome/lsp/BiomeLspWorkspaceSettings.kt
Closes #141
I added support for `workspace/configuration` requests from the server to provide the configuration path without the `--config-path` CLI option.
See https://github.com/biomejs/biome/pull/5093 for server implementation.
=> feat: support workspace/configuration request for providing configuration path

src/main/kotlin/com/github/biomejs/intellijbiome/services/BiomeServerService.kt
Follow-up of #148 
We had to reverse the order of the text edits first or we will get incorrect offsets in some edits.
=> fix: run text edits in a reversed order

sandbox/bar/biome.jsonc, sandbox/bar/package.json, sandbox/foo/biome.jsonc, sandbox/foo/package.json, sandbox/pnpm-lock.yaml, src/main/kotlin/com/github/biomejs/intellijbiome/lsp/BiomeLspServerSupportProvider.kt
Fixes #158 
Previously, the root directory for the LSP server was falled back to the project root when no biome.json(c) is found. However, that causes duplicated instances for a file, after opened a file **outside** Biome-installed directory.
I removed the fallback and now nothing will happen if no biome.json(c) is found.
=> fix: do not fallback to the project root if no biome.json was found

src/main/kotlin/com/github/biomejs/intellijbiome/extensions/FileExt.kt
Fixes #165 
The extension method `VirtualFile.findNearestFile` limits the topmost directory to the specified directory, but not allowed the directory itself. It caused that the plugin can't find biome.json at the project root directory.
Manually tested to open a project with only one biome.json at the root, and a monorepo project with biome.json files for each package.
=> fix: regression where the plugin couldn't find biome.json at the project root

src/main/kotlin/com/github/biomejs/intellijbiome/services/BiomeServerService.kt
On applying text edits returned by the `textDocument/formatting` response, each edit is executed and sent to the LSP server with `textDocument/didChange` notification, which is inefficient. Using `DocumentUtil.executeInBulk` will resolve this and will send all text changes at once.
=> perf: use DocumentUtil.executeInBulk for formatting

src/main/kotlin/com/github/biomejs/intellijbiome/lsp/BiomeLspServerSupportProvider.kt
Fixes #180 
When a project has multiple root folders, the plugin couldn't find the correct base directory which contains the opened file. `Project.guessProjectDir()` doesn't support multi-root projects, so I replaced it with `Project.getBaseDirectories()`.
Manually tested in both a simple project (sandbox) and a multi-root project (the reproduction repo)
=> fix: support project structure with multiple roots

src/main/kotlin/com/github/biomejs/intellijbiome/services/BiomeServerService.kt
Reverts biomejs/biome-intellij#184
Fixes #200 
We have received some reports that an error occurs when formatting on save, and I also experienced this in a specific project:
```
Current operation is not permitted in bulk mode, see Document.isInBulkUpdate() javadoc
```
Reverting the changes for now.
=> fix: revert "perf: use DocumentUtil.executeInBulk for formatting"
